name: Github Action Workflow DEV

on:
  pull_request:
    types:
      - closed

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dev:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'develop'
    uses: martinorue/lab-03-devops/.github/workflows/deploy-to-s3.yml@develop
    with:
      CI_ENV: develop
      CONTENTFUL_ENVIRONMENT: 'develop'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_DEV }}
